# Script to upload project to GitHub
# Generated by Antigravity AI

Write-Host "Initializing Git..." -ForegroundColor Cyan
git init

Write-Host "Adding remote origin..." -ForegroundColor Cyan
git remote add origin https://github.com/Luis4334/X4-1.1-VOX.git

Write-Host "Adding files..." -ForegroundColor Cyan
git add .

Write-Host "Creating initial commit..." -ForegroundColor Cyan
git commit -m "Initial commit of X4-1.1-VOX project"

Write-Host "Setting main branch..." -ForegroundColor Cyan
git branch -M main

Write-Host "Pushing to GitHub..." -ForegroundColor Cyan
Write-Host "Note: If you haven't configured your credentials, a login window may appear." -ForegroundColor Yellow
git push -u origin main

Write-Host "Done!" -ForegroundColor Green
pause
